"""One extra, place-specific FAQ per page."""
FAQ3 = {
"san-jose": ("What if my customers are mostly in Santa Clara or Sunnyvale rather than San Jose?", "Then build for those cities. They are separate markets inside the same county, with their own searches and competitors, and a San Jose page will not carry you there. Start with the one or two cities that bring the most revenue, make the profile and page match, and add others as the business grows into them."),
"sacramento": ("What if I serve both Sacramento and the Roseville area?", "Give each its own page and its own proof. Roseville customers search for Roseville, and the City of Sacramento customers search for neighborhoods like Midtown or Land Park. If your drive time makes serving both unrealistic, choose the one that pays better and be honest about the other on your profile."),
"fresno": ("Do I need all three parts at once?", "No. Most owners fix the biggest leak first. If you have no visibility, start with search. If you have traffic and no calls, start with the site. If you have calls and lose them, start with follow-up. The diagnostic tells you which, and the other two can follow as the first one starts paying."),
"bakersfield": ("What if most of my work comes from oilfield or farm customers?", "Then write for them directly. Name the kinds of work you do, the hours you answer and the area you cover, and make it easy to reach you from a truck. Those customers value plain information and a quick reply. Do not claim expertise you cannot show with real jobs."),
"oakland": ("Is it worth building a separate page for Piedmont?", "Only if you really serve it and customers there search for it. Piedmont is its own city inside Oakland, so people who live there often search by that name. A short, specific page can win those searches. If you rarely work there, skip it and keep your claims tight."),
"long-beach": ("Should I mention the port or the university on my pages?", "Only if they are part of your customer base. A business serving port-related companies or campus staff can say so plainly. Otherwise mentioning landmarks to sound local reads as filler. Mention the places your customers actually come from, and the page will sound local without any extra effort."),
"inland-empire": ("What if I work in both Riverside County and San Bernardino County?", "Customers do not think in counties, they think in cities and freeways. Build pages around the corridors and cities you work in, whichever county they fall in, and keep the service area on your profile consistent with that. The county line matters less than the drive time."),
"orange-county": ("Is a page for Orange County as a whole ever useful?", "Rarely as a primary page. It can work as a hub that links to your individual city pages and states plainly which cities you serve. As the page you expect to rank for a specific search it is weak, because customers search for the city and not for the county."),
"real-estate": ("What should I do before I hire anyone for marketing?", "Check your own license information against the DRE record, make sure your name and brokerage read the same everywhere online, and list the three neighborhoods where you want to be known. Those three steps make any marketing work better, and they cost you an afternoon rather than a budget."),
"salons-med-spas": ("Should I show prices online?", "That is your decision, and different businesses choose differently. I do not publish or set prices for you. What matters is that the service names and descriptions are clear, so a new client knows what they are booking before they arrive, and that anything medical is described accurately."),
"los-angeles-law-firms": ("Can one site serve several Los Angeles offices?", "Yes, with a separate page and a separate profile for each office you really staff. The offices should differ in details a visitor can verify, such as address, hours and attorneys. Pages that only swap the neighborhood name read as thin to both Google and prospective clients."),
"sacramento-contractors": ("Should I mention flood or river conditions?", "Only if you do that kind of work and can describe it from real jobs. The rivers shape parts of the region, but I would not write about conditions you have not worked in. Stick to the work you do and the neighborhoods where you do it."),
"inland-empire-contractors": ("Should I list Palm Springs if I rarely go there?", "No. List only places you will drive to for a normal job. An overlong service area weakens your profile and brings calls you will turn down. You can always add a city later once you have steady work there and some project detail to show."),
"san-diego-real-estate": ("Is a relocation page worth it if I rarely work with military buyers?", "Probably not. Build it only if you have real experience with relocating families, since the page depends on specifics you know firsthand. If your clients are mostly local move-up buyers, put that effort into neighborhood pages instead."),
"orange-county-salons-med-spas": ("Do I need a separate profile for each location?", "Yes. Each location with a staffed address should have its own listing, with its own hours, phone and photos. Sharing one listing across cities confuses customers and weakens the local signal. If you only have one location, focus on making that one listing complete and accurate."),
"law-firms": ("What if my firm has several practice areas?", "Give each its own page, written with the attorney who handles it. A page that tries to cover family law, injury and business matters at once serves none of them well. Start with the practice area that brings the most revenue and add others as the first one performs."),
}
